# Generated by Django 5.0.6 on 2026-01-17 22:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Platform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("jumia", "Jumia"),
                            ("kilimall", "Kilimall"),
                            ("alibaba", "Alibaba"),
                            ("amazon", "Amazon"),
                            ("ebay", "eBay"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("base_url", models.URLField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["name", "is_active"], name="products_pl_name_588962_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=500)),
                ("brand", models.CharField(blank=True, max_length=200)),
                ("category", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField(blank=True)),
                ("image_url", models.URLField(blank=True, max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("search_count", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["name", "-created_at"],
                        name="products_pr_name_1133ad_idx",
                    ),
                    models.Index(
                        fields=["brand", "category"],
                        name="products_pr_brand_b6066d_idx",
                    ),
                    models.Index(
                        fields=["-search_count"], name="products_pr_search__74a601_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductListing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("url", models.URLField(max_length=1000)),
                ("image_url", models.URLField(blank=True, max_length=1000)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "shipping_cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "rating",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                ("review_count", models.IntegerField(blank=True, null=True)),
                ("availability", models.BooleanField(default=True)),
                ("seller_name", models.CharField(blank=True, max_length=200)),
                (
                    "confidence_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="AI confidence score (0-100)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="products.platform",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="listings",
                        to="products.product",
                    ),
                ),
            ],
            options={
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "recorded_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "listing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="products.productlisting",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Price histories",
                "ordering": ["-recorded_at"],
            },
        ),
        migrations.CreateModel(
            name="ScrapingTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task_id", models.CharField(max_length=255, unique=True)),
                ("search_query", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("running", "Running"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("results_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "platform",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.platform",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(max_length=500)),
                (
                    "search_type",
                    models.CharField(
                        choices=[("text", "Text Search"), ("image", "Image Search")],
                        max_length=10,
                    ),
                ),
                ("image_path", models.CharField(blank=True, max_length=500)),
                ("results_count", models.IntegerField(default=0)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "products_found",
                    models.ManyToManyField(
                        blank=True, related_name="searches", to="products.product"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Search histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="productlisting",
            index=models.Index(
                fields=["product", "platform"], name="products_pr_product_0b8d71_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productlisting",
            index=models.Index(
                fields=["price", "availability"], name="products_pr_price_872912_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productlisting",
            index=models.Index(
                fields=["-scraped_at"], name="products_pr_scraped_1dc5c3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productlisting",
            unique_together={("url", "platform")},
        ),
        migrations.AddIndex(
            model_name="pricehistory",
            index=models.Index(
                fields=["listing", "-recorded_at"],
                name="products_pr_listing_32dd81_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="scrapingtask",
            index=models.Index(
                fields=["task_id"], name="products_sc_task_id_1a90d1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapingtask",
            index=models.Index(
                fields=["status", "-created_at"], name="products_sc_status_c8ff23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(
                fields=["-created_at"], name="products_se_created_f8fb1e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="searchhistory",
            index=models.Index(
                fields=["search_type"], name="products_se_search__c01771_idx"
            ),
        ),
    ]
